version: '3.7'

services:

  backend:
    build: .
    container_name: "backend"
    restart: "always"    
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
